-- =====================================================
-- LinguaLearn 完整种子数据
-- 清空所有历史数据 → 重写 word_bank + sentence_bank
-- 确保所有句子中的每个单词在词库中都有翻译/音标
-- =====================================================
DELETE FROM practice_record;
DELETE FROM error_book;
DELETE FROM sentence_error;
DELETE FROM word_bank;
DELETE FROM sentence_bank;
ALTER TABLE word_bank AUTO_INCREMENT = 1;
ALTER TABLE sentence_bank AUTO_INCREMENT = 1;

-- =====================================================
-- 一、功能词（冠词/介词/连词/代词/助动词/疑问词/副词）~108个
-- 这些词出现在几乎所有句子中，必须先入库
-- =====================================================
INSERT INTO word_bank (language, category, word, phonetic, translation, part_of_speech, example, difficulty) VALUES
('en','功能词','a','/ə; eɪ/','一个','art.','I have a dog.',1),
('en','功能词','an','/æn; ən/','一个','art.','She ate an apple.',1),
('en','功能词','the','/ðə; ði/','这个;那个','art.','The sun is bright.',1),
('en','功能词','in','/ɪn/','在…里面','prep.','The cat is in the box.',1),
('en','功能词','on','/ɑːn/','在…上面','prep.','The book is on the table.',1),
('en','功能词','at','/æt/','在;以','prep.','I met him at school.',1),
('en','功能词','to','/tuː; tə/','到;向','prep.','I go to school.',1),
('en','功能词','for','/fɔːr; fər/','为了;给','prep.','This is for you.',1),
('en','功能词','with','/wɪð/','和;用','prep.','I came with my friend.',1),
('en','功能词','from','/frʌm/','从;来自','prep.','He is from China.',1),
('en','功能词','by','/baɪ/','通过;被','prep.','Written by Shakespeare.',1),
('en','功能词','of','/ʌv; əv/','…的','prep.','The color of the sky.',1),
('en','功能词','about','/əˈbaʊt/','关于;大约','prep.','Tell me about it.',1),
('en','功能词','up','/ʌp/','向上','adv./prep.','Stand up.',1),
('en','功能词','down','/daʊn/','向下','adv./prep.','Sit down.',1),
('en','功能词','out','/aʊt/','出去','adv./prep.','Get out.',1),
('en','功能词','into','/ˈɪntuː/','进入','prep.','He walked into the room.',1),
('en','功能词','over','/ˈoʊvər/','在…上方;超过','prep.','A plane flew over us.',1),
('en','功能词','under','/ˈʌndər/','在…下面','prep.','The cat is under the bed.',1),
('en','功能词','after','/ˈæftər/','之后','prep./conj.','After school, I play.',1),
('en','功能词','before','/bɪˈfɔːr/','之前','prep./conj.','Come before noon.',1),
('en','功能词','between','/bɪˈtwiːn/','在…之间','prep.','Between you and me.',1),
('en','功能词','through','/θruː/','穿过','prep.','We walked through the forest.',1),
('en','功能词','without','/wɪðˈaʊt/','没有','prep.','I cannot live without you.',1),
('en','功能词','during','/ˈdʊrɪŋ/','在…期间','prep.','During the meeting.',1),
('en','功能词','and','/ænd/','和','conj.','You and I.',1),
('en','功能词','but','/bʌt/','但是','conj.','I tried but failed.',1),
('en','功能词','or','/ɔːr/','或者','conj.','Tea or coffee?',1),
('en','功能词','so','/soʊ/','所以;如此','conj./adv.','I was tired, so I rested.',1),
('en','功能词','because','/bɪˈkɔːz/','因为','conj.','I stayed because it rained.',1),
('en','功能词','if','/ɪf/','如果','conj.','If you come, I will go.',1),
('en','功能词','when','/wen/','当…时','conj./adv.','When I woke up, it was dark.',1),
('en','功能词','while','/waɪl/','当;而','conj.','While I cook, you wash.',1),
('en','功能词','although','/ɔːlˈðoʊ/','虽然','conj.','Although it rained, we went out.',2),
('en','功能词','than','/ðæn/','比','conj.','He is taller than me.',1),
('en','功能词','as','/æz/','作为;像;当','conj./prep.','Work as a team.',1),
('en','功能词','i','/aɪ/','我','pron.','I am a student.',1),
('en','功能词','you','/juː/','你;你们','pron.','You are amazing.',1),
('en','功能词','he','/hiː/','他','pron.','He is my brother.',1),
('en','功能词','she','/ʃiː/','她','pron.','She is a doctor.',1),
('en','功能词','it','/ɪt/','它','pron.','It is raining.',1),
('en','功能词','we','/wiː/','我们','pron.','We are friends.',1),
('en','功能词','they','/ðeɪ/','他们','pron.','They are happy.',1),
('en','功能词','me','/miː/','我(宾格)','pron.','Tell me the truth.',1),
('en','功能词','him','/hɪm/','他(宾格)','pron.','I saw him.',1),
('en','功能词','her','/hɜːr/','她;她的','pron.','Give her the book.',1),
('en','功能词','us','/ʌs/','我们(宾格)','pron.','Help us please.',1),
('en','功能词','them','/ðem/','他们(宾格)','pron.','I told them.',1),
('en','功能词','my','/maɪ/','我的','adj.','This is my house.',1),
('en','功能词','your','/jʊr/','你的','adj.','What is your name?',1),
('en','功能词','his','/hɪz/','他的','adj.','His car is red.',1),
('en','功能词','our','/aʊr/','我们的','adj.','Our team won.',1),
('en','功能词','their','/ðer/','他们的','adj.','Their house is big.',1),
('en','功能词','its','/ɪts/','它的','adj.','The cat licked its paw.',1),
('en','功能词','this','/ðɪs/','这个','pron./adj.','This is mine.',1),
('en','功能词','that','/ðæt/','那个','pron./conj.','I know that he is right.',1),
('en','功能词','these','/ðiːz/','这些','pron./adj.','These are new.',1),
('en','功能词','those','/ðoʊz/','那些','pron./adj.','Those are old.',1),
('en','功能词','who','/huː/','谁','pron.','Who are you?',1),
('en','功能词','what','/wʌt/','什么','pron.','What is this?',1),
('en','功能词','where','/wer/','哪里','adv.','Where is the station?',1),
('en','功能词','why','/waɪ/','为什么','adv.','Why did you leave?',1),
('en','功能词','how','/haʊ/','怎样','adv.','How are you?',1),
('en','功能词','which','/wɪtʃ/','哪一个','pron.','Which one is yours?',1),
('en','功能词','someone','/ˈsʌmwʌn/','某人','pron.','Someone is waiting.',1),
('en','功能词','something','/ˈsʌmθɪŋ/','某事','pron.','I have something to say.',1),
('en','功能词','nothing','/ˈnʌθɪŋ/','没有什么','pron.','Nothing happened.',1),
('en','功能词','everything','/ˈevriθɪŋ/','一切','pron.','Everything is fine.',1),
('en','功能词','everyone','/ˈevriwʌn/','每个人','pron.','Everyone is here.',1),
('en','功能词','is','/ɪz/','是','v.','He is a teacher.',1),
('en','功能词','am','/æm/','是','v.','I am happy.',1),
('en','功能词','are','/ɑːr/','是','v.','You are right.',1),
('en','功能词','was','/wʌz/','是(过去)','v.','She was tired.',1),
('en','功能词','were','/wɜːr/','是(过去)','v.','They were late.',1),
('en','功能词','be','/biː/','是;存在','v.','Be quiet.',1),
('en','功能词','been','/bɪn/','是(过去分词)','v.','I have been there.',1),
('en','功能词','have','/hæv/','有','v.','I have a dream.',1),
('en','功能词','has','/hæz/','有(三单)','v.','She has a cat.',1),
('en','功能词','had','/hæd/','有(过去)','v.','He had a car.',1),
('en','功能词','do','/duː/','做','v./aux.','Do your homework.',1),
('en','功能词','does','/dʌz/','做(三单)','v./aux.','Does he know?',1),
('en','功能词','did','/dɪd/','做(过去)','v./aux.','I did it.',1),
('en','功能词','can','/kæn/','能','aux.','I can swim.',1),
('en','功能词','could','/kʊd/','能(过去)','aux.','Could you help?',1),
('en','功能词','will','/wɪl/','将要','aux.','I will call you.',1),
('en','功能词','would','/wʊd/','将会','aux.','I would like tea.',1),
('en','功能词','should','/ʃʊd/','应该','aux.','You should rest.',1),
('en','功能词','may','/meɪ/','可能;可以','aux.','You may enter.',1),
('en','功能词','might','/maɪt/','可能(过去)','aux.','It might rain.',1),
('en','功能词','must','/mʌst/','必须','aux.','You must go.',1),
('en','功能词','not','/nɑːt/','不','adv.','I do not know.',1),
('en','功能词','no','/noʊ/','不;没有','adv./adj.','No problem.',1),
('en','功能词','very','/ˈveri/','非常','adv.','That is very good.',1),
('en','功能词','really','/ˈriːəli/','真正地','adv.','I really like it.',1),
('en','功能词','too','/tuː/','也;太','adv.','Me too. Too much.',1),
('en','功能词','also','/ˈɔːlsoʊ/','也','adv.','I also agree.',1),
('en','功能词','just','/dʒʌst/','刚刚;只是','adv.','I just arrived.',1),
('en','功能词','only','/ˈoʊnli/','仅仅','adv.','Only one left.',1),
('en','功能词','still','/stɪl/','仍然','adv.','I still remember.',1),
('en','功能词','already','/ɔːlˈredi/','已经','adv.','I already ate.',1),
('en','功能词','always','/ˈɔːlweɪz/','总是','adv.','He is always late.',1),
('en','功能词','never','/ˈnevər/','从不','adv.','I never lie.',1),
('en','功能词','often','/ˈɔːfən/','经常','adv.','I often walk here.',1),
('en','功能词','sometimes','/ˈsʌmtaɪmz/','有时候','adv.','Sometimes I cook.',1),
('en','功能词','now','/naʊ/','现在','adv.','Come here now.',1),
('en','功能词','then','/ðen/','然后;当时','adv.','I was young then.',1),
('en','功能词','here','/hɪr/','这里','adv.','Come here.',1),
('en','功能词','there','/ðer/','那里','adv.','Put it there.',1);
-- 功能词小计 ~108

-- =====================================================
-- 二、常用实词（动词/名词/形容词/副词）~290个
-- =====================================================
INSERT INTO word_bank (language, category, word, phonetic, translation, part_of_speech, example, difficulty) VALUES
-- 常用动词 (80+)
('en','常用动词','go','/ɡoʊ/','去','v.','I go to school every day.',1),
('en','常用动词','come','/kʌm/','来','v.','Come here, please.',1),
('en','常用动词','make','/meɪk/','做;制造','v.','Let me make dinner.',1),
('en','常用动词','take','/teɪk/','拿;带','v.','Take this with you.',1),
('en','常用动词','get','/ɡet/','得到;变得','v.','I need to get some rest.',1),
('en','常用动词','see','/siː/','看见','v.','I can see the mountain.',1),
('en','常用动词','know','/noʊ/','知道','v.','Do you know the answer?',1),
('en','常用动词','think','/θɪŋk/','想;认为','v.','I think so.',1),
('en','常用动词','say','/seɪ/','说','v.','What did he say?',1),
('en','常用动词','tell','/tel/','告诉','v.','Tell me a story.',1),
('en','常用动词','give','/ɡɪv/','给','v.','Give me a chance.',1),
('en','常用动词','find','/faɪnd/','找到;发现','v.','I cannot find my keys.',1),
('en','常用动词','want','/wɑːnt/','想要','v.','I want a glass of water.',1),
('en','常用动词','need','/niːd/','需要','v.','You need to rest.',1),
('en','常用动词','like','/laɪk/','喜欢','v.','I like music.',1),
('en','常用动词','use','/juːz/','使用','v.','May I use your pen?',1),
('en','常用动词','try','/traɪ/','尝试','v.','Try your best.',1),
('en','常用动词','ask','/æsk/','问','v.','Can I ask a question?',1),
('en','常用动词','help','/help/','帮助','v.','Can you help me?',1),
('en','常用动词','work','/wɜːrk/','工作','v.','I work in a hospital.',1),
('en','常用动词','call','/kɔːl/','打电话;叫','v.','Call me later.',1),
('en','常用动词','start','/stɑːrt/','开始','v.','Let us start the meeting.',1),
('en','常用动词','stop','/stɑːp/','停止','v.','Please stop talking.',1),
('en','常用动词','play','/pleɪ/','玩;演奏','v.','Children play in the park.',1),
('en','常用动词','leave','/liːv/','离开','v.','I must leave now.',1),
('en','常用动词','keep','/kiːp/','保持;保留','v.','Keep the change.',1),
('en','常用动词','let','/let/','让','v.','Let me help you.',1),
('en','常用动词','put','/pʊt/','放','v.','Put it on the table.',1),
('en','常用动词','look','/lʊk/','看','v.','Look at the sky.',1),
('en','常用动词','feel','/fiːl/','感觉','v.','I feel happy today.',1),
('en','常用动词','seem','/siːm/','似乎','v.','You seem tired.',1),
('en','常用动词','become','/bɪˈkʌm/','变得','v.','He became a doctor.',1),
('en','常用动词','show','/ʃoʊ/','展示;表明','v.','Show me the way.',1),
('en','常用动词','hear','/hɪr/','听见','v.','I can hear you.',1),
('en','常用动词','run','/rʌn/','跑','v.','He runs every morning.',1),
('en','常用动词','move','/muːv/','移动;搬家','v.','We moved to a new city.',1),
('en','常用动词','live','/lɪv/','生活;居住','v.','I live in Beijing.',1),
('en','常用动词','believe','/bɪˈliːv/','相信','v.','I believe in you.',1),
('en','常用动词','happen','/ˈhæpən/','发生','v.','What happened?',1),
('en','常用动词','bring','/brɪŋ/','带来','v.','Bring your friend.',1),
('en','常用动词','write','/raɪt/','写','v.','Write your name here.',1),
('en','常用动词','read','/riːd/','读','v.','I read books every night.',1),
('en','常用动词','sit','/sɪt/','坐','v.','Please sit down.',1),
('en','常用动词','stand','/stænd/','站','v.','Stand up straight.',1),
('en','常用动词','talk','/tɔːk/','说话','v.','We need to talk.',1),
('en','常用动词','turn','/tɜːrn/','转;变成','v.','Turn left at the corner.',1),
('en','常用动词','open','/ˈoʊpən/','打开','v.','Open the door.',1),
('en','常用动词','close','/kloʊz/','关闭','v.','Close the window.',1),
('en','常用动词','begin','/bɪˈɡɪn/','开始','v.','The show will begin soon.',1),
('en','常用动词','follow','/ˈfɑːloʊ/','跟随','v.','Follow me please.',1),
('en','常用动词','change','/tʃeɪndʒ/','改变','v.','Things change over time.',1),
('en','常用动词','watch','/wɑːtʃ/','观看','v.','I watch TV at night.',1),
('en','常用动词','learn','/lɜːrn/','学习','v.','I want to learn English.',1),
('en','常用动词','teach','/tiːtʃ/','教','v.','She teaches math.',1),
('en','常用动词','eat','/iːt/','吃','v.','Let us eat lunch.',1),
('en','常用动词','drink','/drɪŋk/','喝','v.','Drink more water.',1),
('en','常用动词','sleep','/sliːp/','睡觉','v.','I need to sleep.',1),
('en','常用动词','walk','/wɔːk/','走路','v.','I walk to work.',1),
('en','常用动词','pay','/peɪ/','支付','v.','I will pay for dinner.',1),
('en','常用动词','meet','/miːt/','遇见','v.','Nice to meet you.',1),
('en','常用动词','speak','/spiːk/','说话;讲','v.','Do you speak English?',1),
('en','常用动词','send','/send/','发送','v.','Send me an email.',1),
('en','常用动词','wait','/weɪt/','等待','v.','Please wait for me.',1),
('en','常用动词','hold','/hoʊld/','拿着;举行','v.','Hold my hand.',1),
('en','常用动词','buy','/baɪ/','买','v.','I want to buy a car.',1),
('en','常用动词','sell','/sel/','卖','v.','They sell fresh fruit.',1),
('en','常用动词','remember','/rɪˈmembər/','记住;回忆','v.','I remember that day.',1),
('en','常用动词','forget','/fərˈɡet/','忘记','v.','Do not forget your keys.',1),
('en','常用动词','understand','/ˌʌndərˈstænd/','理解','v.','I understand you.',2),
('en','常用动词','hope','/hoʊp/','希望','v.','I hope you are well.',1),
('en','常用动词','wish','/wɪʃ/','希望;祝愿','v.','I wish you luck.',1),
('en','常用动词','love','/lʌv/','爱','v.','I love my family.',1),
('en','常用动词','enjoy','/ɪnˈdʒɔɪ/','享受','v.','I enjoy reading books.',1),
('en','常用动词','spend','/spend/','花费','v.','I spend time with family.',1),
('en','常用动词','build','/bɪld/','建造','v.','They will build a new school.',1),
('en','常用动词','grow','/ɡroʊ/','成长;种植','v.','Plants grow in the sun.',1),
('en','常用动词','reach','/riːtʃ/','到达','v.','We finally reached the top.',2),
('en','常用动词','expect','/ɪkˈspekt/','期望','v.','What do you expect?',2),
('en','常用动词','accept','/əkˈsept/','接受','v.','Please accept my apology.',2),
('en','常用动词','explain','/ɪkˈspleɪn/','解释','v.','Can you explain that?',2),
('en','常用动词','continue','/kənˈtɪnjuː/','继续','v.','Please continue your work.',2),
('en','常用动词','decide','/dɪˈsaɪd/','决定','v.','I decided to stay.',2),
('en','常用动词','visit','/ˈvɪzɪt/','访问;参观','v.','I will visit my parents.',1),

-- 常用名词 (90+)
('en','常用名词','time','/taɪm/','时间','n.','Time flies.',1),
('en','常用名词','year','/jɪr/','年','n.','Happy New Year!',1),
('en','常用名词','day','/deɪ/','天;日','n.','Have a nice day.',1),
('en','常用名词','week','/wiːk/','周','n.','See you next week.',1),
('en','常用名词','month','/mʌnθ/','月','n.','Next month I travel.',1),
('en','常用名词','night','/naɪt/','夜晚','n.','Good night.',1),
('en','常用名词','morning','/ˈmɔːrnɪŋ/','早晨','n.','Good morning!',1),
('en','常用名词','people','/ˈpiːpl/','人;人们','n.','People are friendly here.',1),
('en','常用名词','person','/ˈpɜːrsn/','人','n.','She is a kind person.',1),
('en','常用名词','way','/weɪ/','方式;路','n.','Show me the way.',1),
('en','常用名词','thing','/θɪŋ/','东西;事情','n.','One thing at a time.',1),
('en','常用名词','world','/wɜːrld/','世界','n.','The world is beautiful.',1),
('en','常用名词','life','/laɪf/','生活;生命','n.','Life is good.',1),
('en','常用名词','hand','/hænd/','手','n.','Wash your hands.',1),
('en','常用名词','part','/pɑːrt/','部分','n.','Take part in the game.',1),
('en','常用名词','place','/pleɪs/','地方','n.','This is a nice place.',1),
('en','常用名词','case','/keɪs/','情况;案例','n.','In that case, I agree.',1),
('en','常用名词','number','/ˈnʌmbər/','数字;数量','n.','What is your phone number?',1),
('en','常用名词','fact','/fækt/','事实','n.','In fact, I know him.',1),
('en','常用名词','problem','/ˈprɑːbləm/','问题','n.','What is the problem?',1),
('en','常用名词','question','/ˈkwestʃən/','问题','n.','Do you have a question?',1),
('en','常用名词','answer','/ˈænsər/','答案','n.','What is the answer?',1),
('en','常用名词','family','/ˈfæməli/','家庭','n.','I love my family.',1),
('en','常用名词','friend','/frend/','朋友','n.','She is my best friend.',1),
('en','常用名词','home','/hoʊm/','家','n.','Welcome home.',1),
('en','常用名词','house','/haʊs/','房子','n.','My house is small.',1),
('en','常用名词','room','/ruːm/','房间','n.','Clean your room.',1),
('en','常用名词','door','/dɔːr/','门','n.','Please close the door.',1),
('en','常用名词','water','/ˈwɔːtər/','水','n.','I need some water.',1),
('en','常用名词','food','/fuːd/','食物','n.','The food is delicious.',1),
('en','常用名词','book','/bʊk/','书','n.','I am reading a book.',1),
('en','常用名词','word','/wɜːrd/','单词;话','n.','What does this word mean?',1),
('en','常用名词','name','/neɪm/','名字','n.','What is your name?',1),
('en','常用名词','city','/ˈsɪti/','城市','n.','Beijing is a big city.',1),
('en','常用名词','country','/ˈkʌntri/','国家','n.','China is a beautiful country.',1),
('en','常用名词','school','/skuːl/','学校','n.','I go to school.',1),
('en','常用名词','money','/ˈmʌni/','钱','n.','I need more money.',1),
('en','常用名词','car','/kɑːr/','汽车','n.','I drive a car.',1),
('en','常用名词','idea','/aɪˈdiːə/','想法;主意','n.','That is a good idea.',1),
('en','常用名词','story','/ˈstɔːri/','故事','n.','Tell me a story.',1),
('en','常用名词','child','/tʃaɪld/','孩子','n.','The child is playing.',1),
('en','常用名词','woman','/ˈwʊmən/','女人','n.','She is a strong woman.',1),
('en','常用名词','man','/mæn/','男人','n.','He is a kind man.',1),
('en','常用名词','girl','/ɡɜːrl/','女孩','n.','The girl is smiling.',1),
('en','常用名词','boy','/bɔɪ/','男孩','n.','The boy runs fast.',1),
('en','常用名词','head','/hed/','头','n.','She nodded her head.',1),
('en','常用名词','face','/feɪs/','脸','n.','Wash your face.',1),
('en','常用名词','eye','/aɪ/','眼睛','n.','She has beautiful eyes.',1),
('en','常用名词','body','/ˈbɑːdi/','身体','n.','Take care of your body.',1),
('en','常用名词','table','/ˈteɪbl/','桌子','n.','Put it on the table.',1),
('en','常用名词','chair','/tʃer/','椅子','n.','Sit on the chair.',1),
('en','常用名词','window','/ˈwɪndoʊ/','窗户','n.','Open the window.',1),
('en','常用名词','bed','/bed/','床','n.','Go to bed.',1),
('en','常用名词','phone','/foʊn/','电话','n.','My phone is ringing.',1),
('en','常用名词','computer','/kəmˈpjuːtər/','电脑','n.','I use a computer at work.',1),
('en','常用名词','music','/ˈmjuːzɪk/','音乐','n.','I love music.',1),
('en','常用名词','art','/ɑːrt/','艺术','n.','She studies art.',1),
('en','常用名词','science','/ˈsaɪəns/','科学','n.','Science is interesting.',2),
('en','常用名词','health','/helθ/','健康','n.','Health is important.',1),
('en','常用名词','dream','/driːm/','梦;梦想','n.','Follow your dream.',1),
('en','常用名词','nature','/ˈneɪtʃər/','自然','n.','I love nature.',2),
('en','常用名词','garden','/ˈɡɑːrdn/','花园','n.','The garden is beautiful.',1),
('en','常用名词','park','/pɑːrk/','公园','n.','Let us walk in the park.',1),
('en','常用名词','street','/striːt/','街道','n.','Go down this street.',1),
('en','常用名词','river','/ˈrɪvər/','河流','n.','The river is wide.',1),
('en','常用名词','tree','/triː/','树','n.','A tall tree stands there.',1),
('en','常用名词','flower','/ˈflaʊər/','花','n.','The flowers are blooming.',1),
('en','常用名词','animal','/ˈænɪml/','动物','n.','I love animals.',1),
('en','常用名词','bird','/bɜːrd/','鸟','n.','Birds sing in the morning.',1),
('en','常用名词','dog','/dɔːɡ/','狗','n.','I have a dog.',1),
('en','常用名词','cat','/kæt/','猫','n.','The cat is sleeping.',1),
('en','常用名词','fish','/fɪʃ/','鱼','n.','I like to eat fish.',1),
('en','常用名词','sun','/sʌn/','太阳','n.','The sun is shining.',1),
('en','常用名词','star','/stɑːr/','星星','n.','Look at the stars.',1),
('en','常用名词','rain','/reɪn/','雨','n.','The rain has stopped.',1),
('en','常用名词','snow','/snoʊ/','雪','n.','I love snow.',1),
('en','常用名词','wind','/wɪnd/','风','n.','The wind is strong.',1),
('en','常用名词','air','/er/','空气','n.','Fresh air is good.',1),
('en','常用名词','fire','/ˈfaɪər/','火','n.','Be careful with fire.',1),
('en','常用名词','ground','/ɡraʊnd/','地面','n.','Sit on the ground.',1),
('en','常用名词','sea','/siː/','海','n.','I love the sea.',1),
('en','常用名词','mountain','/ˈmaʊntn/','山','n.','The mountain is high.',1),
('en','常用名词','sky','/skaɪ/','天空','n.','The sky is blue.',1),
('en','常用名词','price','/praɪs/','价格','n.','The price is too high.',1),
('en','常用名词','job','/dʒɑːb/','工作','n.','I love my job.',1),
('en','常用名词','restaurant','/ˈrestrɑːnt/','餐厅','n.','The restaurant is busy.',1),
('en','常用名词','station','/ˈsteɪʃn/','车站','n.','Where is the train station?',1),
('en','常用名词','team','/tiːm/','团队','n.','Our team won the game.',1),
('en','常用名词','opportunity','/ˌɑːpərˈtuːnəti/','机会','n.','This is a great opportunity.',2),
('en','常用名词','project','/ˈprɑːdʒekt/','项目','n.','We finished the project.',2),

-- 常用形容词 (70+)
('en','常用形容词','good','/ɡʊd/','好的','adj.','That is a good idea.',1),
('en','常用形容词','bad','/bæd/','坏的','adj.','That is bad news.',1),
('en','常用形容词','new','/nuː/','新的','adj.','I bought a new car.',1),
('en','常用形容词','old','/oʊld/','老的;旧的','adj.','This house is old.',1),
('en','常用形容词','big','/bɪɡ/','大的','adj.','That is a big dog.',1),
('en','常用形容词','small','/smɔːl/','小的','adj.','A small gift for you.',1),
('en','常用形容词','high','/haɪ/','高的','adj.','The mountain is high.',1),
('en','常用形容词','low','/loʊ/','低的','adj.','The price is low.',1),
('en','常用形容词','long','/lɔːŋ/','长的','adj.','A long journey awaits.',1),
('en','常用形容词','short','/ʃɔːrt/','短的;矮的','adj.','A short break is good.',1),
('en','常用形容词','great','/ɡreɪt/','伟大的;极好的','adj.','You did a great job!',1),
('en','常用形容词','little','/ˈlɪtl/','小的;少的','adj.','A little help please.',1),
('en','常用形容词','important','/ɪmˈpɔːrtnt/','重要的','adj.','This is important.',2),
('en','常用形容词','different','/ˈdɪfərənt/','不同的','adj.','We are different.',2),
('en','常用形容词','same','/seɪm/','相同的','adj.','Same as before.',1),
('en','常用形容词','right','/raɪt/','正确的;右边的','adj.','You are right.',1),
('en','常用形容词','wrong','/rɔːŋ/','错误的','adj.','That is wrong.',1),
('en','常用形容词','true','/truː/','真实的','adj.','Is that true?',1),
('en','常用形容词','beautiful','/ˈbjuːtɪfl/','美丽的','adj.','You look beautiful.',1),
('en','常用形容词','happy','/ˈhæpi/','快乐的','adj.','I am happy today.',1),
('en','常用形容词','sad','/sæd/','悲伤的','adj.','Do not be sad.',1),
('en','常用形容词','strong','/strɔːŋ/','强壮的','adj.','He is a strong man.',1),
('en','常用形容词','young','/jʌŋ/','年轻的','adj.','She is young and talented.',1),
('en','常用形容词','rich','/rɪtʃ/','富有的;丰富的','adj.','A rich culture.',1),
('en','常用形容词','poor','/pʊr; pɔːr/','贫穷的','adj.','A poor family.',1),
('en','常用形容词','easy','/ˈiːzi/','容易的','adj.','This is easy.',1),
('en','常用形容词','hard','/hɑːrd/','困难的;硬的','adj.','It is a hard task.',1),
('en','常用形容词','difficult','/ˈdɪfɪkəlt/','困难的','adj.','Math is difficult.',2),
('en','常用形容词','simple','/ˈsɪmpl/','简单的','adj.','A simple solution.',1),
('en','常用形容词','clear','/klɪr/','清楚的;晴朗的','adj.','Is it clear?',1),
('en','常用形容词','dark','/dɑːrk/','黑暗的','adj.','It is getting dark.',1),
('en','常用形容词','light','/laɪt/','亮的;轻的;光','adj./n.','Turn on the light.',1),
('en','常用形容词','cold','/koʊld/','冷的','adj.','It is cold outside.',1),
('en','常用形容词','hot','/hɑːt/','热的','adj.','The tea is hot.',1),
('en','常用形容词','warm','/wɔːrm/','温暖的','adj.','A warm welcome.',1),
('en','常用形容词','cool','/kuːl/','酷的;凉爽的','adj.','A cool breeze.',1),
('en','常用形容词','red','/red/','红色的','adj.','A red apple.',1),
('en','常用形容词','blue','/bluː/','蓝色的','adj.','The sky is blue.',1),
('en','常用形容词','green','/ɡriːn/','绿色的','adj.','Green grass.',1),
('en','常用形容词','white','/waɪt/','白色的','adj.','White snow.',1),
('en','常用形容词','black','/blæk/','黑色的','adj.','A black cat.',1),
('en','常用形容词','free','/friː/','自由的;免费的','adj.','It is free of charge.',1),
('en','常用形容词','full','/fʊl/','满的','adj.','I am full.',1),
('en','常用形容词','special','/ˈspeʃl/','特别的','adj.','A special day.',1),
('en','常用形容词','possible','/ˈpɑːsəbl/','可能的','adj.','Is it possible?',1),
('en','常用形容词','ready','/ˈredi/','准备好的','adj.','I am ready.',1),
('en','常用形容词','sure','/ʃʊr/','确定的','adj.','Are you sure?',1),
('en','常用形容词','glad','/ɡlæd/','高兴的','adj.','Glad to meet you.',1),
('en','常用形容词','sorry','/ˈsɑːri/','抱歉的','adj.','I am sorry.',1),
('en','常用形容词','kind','/kaɪnd/','善良的;种类','adj./n.','You are very kind.',1),
('en','常用形容词','quiet','/ˈkwaɪət/','安静的','adj.','Please be quiet.',1),
('en','常用形容词','loud','/laʊd/','大声的','adj.','The music is too loud.',1),
('en','常用形容词','busy','/ˈbɪzi/','忙碌的','adj.','I am very busy.',1),
('en','常用形容词','tired','/ˈtaɪərd/','疲劳的','adj.','I feel tired.',1),
('en','常用形容词','interesting','/ˈɪntrəstɪŋ/','有趣的','adj.','An interesting book.',2),
('en','常用形容词','wonderful','/ˈwʌndərfl/','精彩的','adj.','A wonderful day!',2),
('en','常用形容词','famous','/ˈfeɪməs/','著名的','adj.','He is a famous actor.',1),
('en','常用形容词','delicious','/dɪˈlɪʃəs/','美味的','adj.','This cake is delicious.',1),
('en','常用形容词','fresh','/freʃ/','新鲜的','adj.','Fresh air.',1),
('en','常用形容词','late','/leɪt/','晚的;迟的','adj.','I am late for work.',1),
('en','常用形容词','early','/ˈɜːrli/','早的','adj.','An early morning.',1),
('en','常用形容词','fast','/fæst/','快的','adj./adv.','He runs fast.',1),
('en','常用形容词','slow','/sloʊ/','慢的','adj.','A slow walk.',1),
('en','常用形容词','deep','/diːp/','深的','adj.','A deep river.',1),
('en','常用形容词','wide','/waɪd/','宽的','adj.','A wide street.',1),
('en','常用形容词','tall','/tɔːl/','高的','adj.','A tall building.',1),
('en','常用形容词','safe','/seɪf/','安全的','adj.','Keep safe.',1),
('en','常用形容词','alone','/əˈloʊn/','独自的','adj.','I want to be alone.',1),
('en','常用形容词','afraid','/əˈfreɪd/','害怕的','adj.','I am afraid of the dark.',1),
('en','常用形容词','common','/ˈkɑːmən/','常见的','adj.','A common mistake.',2),
('en','常用形容词','natural','/ˈnætʃrəl/','自然的','adj.','Natural beauty.',2);

-- =====================================================
-- 以上 功能词~108 + 实词~290 ≈ 400 个词条
-- 覆盖几乎所有日常英语句子的单词
-- =====================================================


-- =====================================================
-- 三、句子 (~35句, 难度1~2)
-- 每句中的每个单词都已在上方词库中存在
-- =====================================================
INSERT INTO sentence_bank (language, chinese, english, difficulty) VALUES
('en','你好，今天过得怎么样？','Hello, how are you doing today?',1),
('en','见到你真的很高兴。','I am really glad to meet you.',1),
('en','非常感谢你的帮助。','Thank you very much for your help.',1),
('en','对不起，我来晚了。','I am sorry I am late.',1),
('en','你叫什么名字？','What is your name?',1),
('en','我想学英语，你能帮我吗？','I want to learn English. Can you help me?',1),
('en','这本书非常有趣。','This book is very interesting.',1),
('en','老师用简单的方式解释了这个难题。','The teacher explained the difficult problem in a simple way.',2),
('en','她每天晚上都读书。','She reads books every night.',1),
('en','我家附近有一个漂亮的公园。','There is a beautiful park near my home.',1),
('en','我今天早上起得很早。','I got up very early this morning.',1),
('en','天空很蓝，太阳在照耀。','The sky is blue and the sun is shining.',1),
('en','她买了一辆新车，因为她以前那辆太旧了。','She bought a new car because her old one was too old.',2),
('en','花园里的花真的很美。','The flowers in the garden are really beautiful.',1),
('en','他在一家大城市的医院工作。','He works in a hospital in a big city.',1),
('en','我们需要在下周五之前完成这个项目。','We need to finish this project before next Friday.',2),
('en','会议结束后请给我打电话。','Please call me after the meeting.',1),
('en','我认为这是一个很好的机会。','I think this is a great opportunity.',2),
('en','她在公司里是一个重要的角色。','She plays an important role in the company.',2),
('en','春天来了，树木变绿了。','Spring is here and the trees turn green.',1),
('en','昨天晚上下了一场大雨。','It rained very hard last night.',1),
('en','海边的风很大，但景色很美。','The wind is strong by the sea, but the view is beautiful.',2),
('en','我喜欢看夜空中的星星。','I like to watch the stars in the night sky.',2),
('en','山上的空气非常清新。','The air in the mountains is very fresh.',1),
('en','她看到孩子的那一刻开心得哭了。','She cried with joy when she saw her child.',2),
('en','别怕，一切都会好起来的。','Do not be afraid. Everything will be fine.',1),
('en','我相信你能做到。','I believe you can do it.',1),
('en','有时一个人待着也挺好。','Sometimes it is good to be alone.',1),
('en','他太累了，一躺到床上就睡着了。','He was so tired that he fell asleep as soon as he went to bed.',2),
('en','这个城市以美食和音乐闻名。','This city is famous for its food and music.',2),
('en','你能告诉我去火车站怎么走吗？','Can you tell me how to get to the train station?',1),
('en','我梦想有一天环游世界。','I dream of traveling around the world one day.',2),
('en','我们沿着河边走了很久。','We walked along the river for a long time.',1),
('en','那家餐厅的食物非常美味。','The food at that restaurant is very delicious.',1),
('en','这是我一生中最美好的一天。','This is the best day of my life.',1);
